[package]
name = "softfloat"
version = "0.1.0"
authors = ["SoyaOhnishi <soya.ohnishi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.5"
log = "0.4"

[dev-dependencies]
rand = "0.7"